### ISSUE TITLE
Readme issues

### ISSUE THREAD

**Issue by blischalk** [vishesh/elasticsearch.rkt#1]
The readme specifies:

```
(es/index-create "twitter")
```

but I believe a client needs to be specified like:

```
(es/index-create DC "twitter")
```

The index-delete line specifies a client called C:

```
(es/index-delete C "twitter")
```

but the struct is defined as DC I believe the line should be:

```
(es/index-delete DC "twitter")
```

Also, when following the directions in the README and executing the following at the Racket REPL:

```
(es/index-create DC "twitter")
```

I get the following error:

```
client-ssl?: contract violation
  expected: client?
  given: #<es/client>
  context...:
```

I'm not familiar enough with Racket yet to understand what is going on with this.  It seems like some sort of namespacing issue.
